name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.10.14
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
    - name: Run tests
      run: |
        poetry run pytest
    - name: Run linter
      run: |
        poetry run flake8 .
